---
# Remove old or conflicting Docker packages
- name: Ensure old versions of Docker are not installed
  package:
    name: "{{ docker_obsolete_packages }}"
    state: absent

# Add Docker repository (openSUSE / SLES)
- name: Add Docker repository
  zypper_repository:
    name: "docker-ce"
    repo: "{{ docker_zypper_repo_url }}"
    state: present
    auto_import_keys: yes
  when: docker_add_repo | bool

# Refresh zypper repositories to pick up the new Docker repo
- name: Refresh zypper repositories
  command: zypper --non-interactive refresh
  when: docker_add_repo | bool

# Install Docker packages
- name: Ensure Docker packages are installed
  ansible.legacy.zypper:
    name: "{{ docker_packages }}"
    state: present
